### ISSUE TITLE
Many errors in Swift4 when building finished

### ISSUE THREAD

**Issue by IIDreams** [eggswift/pull-to-refresh#106]
Hello, there are many errors when building finished with Swift4 in Xcode9, how to deal with it, thank you.

**Comment by shijian123** [comment]
me too

**Comment by siberianisaev** [comment]
Waiting for repo owner. Please temporary use `pod 'ESPullToRefresh', :git => 'https://github.com/eggswift/pull-to-refresh.git', :commit => '73d64205ba6d8a3737ee042b1c166c6caa837011'`

**Comment by IIDreams** [comment]
It works now，thank you.
