### ISSUE TITLE
当TableViewController嵌入到一个Navigation里面时，下拉刷新后，第一个Cell会被导航条遮盖

### ISSUE THREAD

**Issue by rexzhang** [eggswift/pull-to-refresh#11]
OSX 10.11.5
xcode 7.3.1
ESPullToRefresh 1.0.4

**Comment by eggswift** [comment]
你好，请问你设置TableViewController 'self.automaticallyAdjustsScrollViewInsets = false' 了么？

**Comment by tangjianft** [comment]
我今天下载最新的版本也遇到这个问题，请问如何解决？

**Comment by eggswift** [comment]
TableViewController 'self.automaticallyAdjustsScrollViewInsets = false'  可以解决这个问题
或者尝试使用最新版本～
