### ISSUE TITLE
This was called for many times, anything wrong with using it?

### ISSUE THREAD

**Issue by alexliubj** [eggswift/pull-to-refresh#12]
`[self.contentView es_addInfiniteScrollingWithHandler:^{
        
        if (numeroCapituloAux != (int)book.caps) {
            [self carregaCapituloWithNumeroCapitulo:++numeroCapituloAux];
        }
        
        [self.contentView es_stopLoadingMore];
        
        self.contentView.contentOffset = CGPointZero;
        [self.contentView scrollRangeToVisible:NSMakeRange(0, 1)];

    }];`

**Comment by alexliubj** [comment]
The following was called many times.

es_addInfiniteScrollingWithHandler

**Comment by hoody4032** [comment]
I found an issue. Not sure if it is related to this.

When I do infiniteScrolling, it sometimes does not return the right value.

For example, my app pulls data from a server. Every time when I scroll to the bottom, it will pull news from the previous day.

From my experience, it sometimes pulls the wrong date. For example, my current date is today. When I scroll to the bottom, it should pull yesterday's data, but instead, sometimes it pulls data from two days ago.

This is not consistent. Sometime it works, sometime not.

**Comment by eggswift** [comment]
This is a good question! I have already added an UITextView example that you can have a look. If you still have problems, please feedback in this issue. : )

**Comment by eggswift** [comment]
#13

**Comment by alexliubj** [comment]
I found another issue that i'm not sure if it is caused by this library.
I'm using UITextview and integrated with your library, when I scroll down a little bit and long press the UITextview, it will jump back to the top. I mean it will scroll all the way to the top of my UITextview. But it won't happen if the long press happened when my UITextview didn't scroll down.

**Comment by eggswift** [comment]
This is so strange 😂, it doesn't happen in my demo. Would you like to share a demo? It will help me to fix this problem.  

---- didn't scroll down and long press
![img_1111](https://cloud.githubusercontent.com/assets/15206466/16511217/afc42c30-3f80-11e6-86ad-443b4cc16844.PNG)

---- scroll down a little bit and long press
![img_1112](https://cloud.githubusercontent.com/assets/15206466/16511218/b02d221c-3f80-11e6-8583-78625ca13b3a.PNG)

**Comment by alexliubj** [comment]
Close it as it was not caused by this library :)
