### ISSUE TITLE
刷新的字眼能设置为中文吗

### ISSUE THREAD

**Issue by SiuyuenChow** [eggswift/pull-to-refresh#129]
- - 好像找不到设置中文的api？

**Comment by GorXion** [comment]
let animator = ESRefreshHeaderAnimator()
animator.pullToRefreshDescription = "下拉刷新"
animator.releaseToRefreshDescription = "松开刷新"
animator.loadingDescription = "加载中..."
tableView.es.addPullToRefresh(animator: animator) {}
