### ISSUE TITLE
infinite scroll 的问题

### ISSUE THREAD

**Issue by hoody4032** [eggswift/pull-to-refresh#13]
我的app是开始时显示当天的内容，当tableview滑到底部时会从server端抓前一天的内容。

但是我发现有时不是抓前一天的内容，而是抓前几天的内容。也就是时间都乱了。

但不是都这样。很不稳定。有时显示的正常的。有时就不对。

我看到另一个issue似乎提到了这个问题。不知道和我提的是否一样。

您能看看么？

多谢。

**Comment by eggswift** [comment]
hi,你可以分享一个问题demo给我么？如果这是一个bug，我可以更快fix它。 : )

**Comment by hoody4032** [comment]
抱歉我不能把整个project分享给您。也无法把网站的地址分享给您。我可以把我的相关的code贴上来。您能看看我是否做错了什么。

`        self.tableView.es_addInfiniteScrolling { 
            [weak self] in
                        
            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), {
                if((self?.category.hasSectionTitle) == true) {
                    self?.modelManager.currentDate = NSDate.getYesterday((self?.modelManager.currentDate)!)
                    print(self?.modelManager.currentDate)
                } else {
                    self?.modelManager.currentUrl = (self?.category.url)!
                    self?.modelManager.currentPage += 1
                }

                self?.modelManager.getData()
                
                dispatch_async(dispatch_get_main_queue(), {
                    self?.tableView.reloadData()
                    self?.tableView.es_stopLoadingMore() 
                })
            })
        }`

> print(self?.modelManager.currentDate)

从里面的print语句，应该打印当前的日期。我发现每次我scroll到底部时，它不是打印一天的日期，而是多数时候是打印两天的日期。请问您能分析一下是我的code的问题还是您的？

多谢。

**Comment by eggswift** [comment]
self?.modelManager.getData()
请问这个函数具体实现了什么？
如果getData()是一个异步读取数据并且reload TableView的方法的话，可能会出现问题。
建议将刷新所需要执行的reloadData、insertData、deleteData等都放在闭包中。异步的要等待异步函数执行完再调用reloadData()和es_stopLoadingMore()
如果依然有问题，你可以针对这个问题做一个小demo，并不需要您工程的代码～ 感谢您积极维护这个开源组件。

**Comment by hoody4032** [comment]
这个函数从server端抓数据。每次滑到最低端时，就去抓前一天的数据。

`   func getData() {
        Alamofire.request(.GET, currentUrl)
            .validate()
            .responseJSON { response in
                if let JSON = response.result.value {
                    
                    let data = JSON as! NSArray
                    if(self.bHasSection) {
                        
                        let item = data[0] as! NSDictionary
                        let section = self.JSON2Section(item)
                        
                        self.sections.append(section)
                        self.delegate?.dataUpdated()
                        
                        if self.currentUrl == K.Network.startURL {
                            self.currentDate = section.date!
                        }
                    } else {
                        if self.sections.count == 0 {
                            let section = Section()
                            self.sections.append(section)
                        }
                        self.sections[0].articles! += self.JSON2Array(data)
                        self.delegate?.dataUpdated()
                    }
                }
        }
    }`

**Comment by eggswift** [comment]
你的逻辑有问题，建议在request回调后停止刷新事件。

**Comment by hoody4032** [comment]
我查了一下，应该和getData()没有关系。我把这一行注释了，还是会一次打印好几天的日期。

我用您在github上的例子做了一个小的demo，能够重复这个错误。

在您的DefaultTableViewController.swift的文件中做如下改动。

把您的

```
self.tableView.es_addInfiniteScrolling {
...
...
...
}
```

这个block用以下代码代替：
```
        self.tableView.es_addInfiniteScrolling {
            [weak self] in
            
            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), {
                self!.i += 1
                print(self!.i)
                
                dispatch_async(dispatch_get_main_queue(), {
                    //                    self?.tableView.reloadData()
                    self?.tableView.es_stopLoadingMore()
                })
            })
        }
```

这个i在DefaultTableViewController开始定义

`var i = 0`

当您scroll到底部时，您可以看到不是每次都打印一个数字。我的是每次打印3个数字。当我第一次滑到底部时，不是打印1，而是打印1，2，3.再滑到底部，又打印4，5，6.

您看看这样设置有问题么？您能不能重复这个问题？

**Comment by hoody4032** [comment]
我发现这个好像和delay的时间有关。这次我用的是您提供的default的例子（DefaultTableViewController.swift）。

以下是您的原始代码：

```
        self.tableView.es_addInfiniteScrolling {
            [weak self] in
            let minseconds = 3.0 * Double(NSEC_PER_SEC)
            let dtime = dispatch_time(DISPATCH_TIME_NOW, Int64(minseconds))
            dispatch_after(dtime, dispatch_get_main_queue() , {
                self?.page += 1
                if self?.page <= 3 {
                    for _ in 1...8{
                        self?.array.append(" ")
                    }
                    self?.tableView.reloadData()
                    self?.tableView.es_stopLoadingMore()
                } else {
                    self?.tableView.es_noticeNoMoreData()
                }
            })
        }
```

我稍微做了改动。

```
        self.tableView.es_addInfiniteScrolling {
            [weak self] in
            let minseconds = 0.001 * Double(NSEC_PER_SEC)
            let dtime = dispatch_time(DISPATCH_TIME_NOW, Int64(minseconds))
            dispatch_after(dtime, dispatch_get_main_queue() , {
                self?.page += 1
                print(self?.page)
                if self?.page <= 100 {
                    for _ in 1...2{
                        self?.array.append(String(self?.page))
                    }
                    self?.tableView.reloadData()
                    self?.tableView.es_stopLoadingMore()
                } else {
                    self?.tableView.es_noticeNoMoreData()
                }
            })
        }
```

以下是改动。
1）添加了打印语句，打印page
2）把delay时间从3.0秒改成了0.001秒
3）把for loop从1到8改成了1到2
4）把page的限制从3改到了100

如果您观察打印的结果，您会发现您的原始code工作正常，每次scroll只打印1个数字。而您如果用更正后的代码，每次不确定，可能打印一个数字，也可能打印2个或多个。

您能看看么？

**Comment by eggswift** [comment]
是scrollView的decelerating引起的问题，会导致调用多次。Fixed！ ： ）

**Comment by hoody4032** [comment]
太好了！请问我能用pod install来按装新版本么？

多谢！

**Comment by eggswift** [comment]
明天发布新的version，再优化一些细节，非常感谢你的帮助，有什么需要改进的随时issue～
