### ISSUE TITLE
UITableview中addInfiniteScrolling无限循环调用

### ISSUE THREAD

**Issue by lzj509649444** [eggswift/pull-to-refresh#132]
xcode9，ios11 模拟器上面

**Comment by kikohz** [comment]
我也碰到了，iPhone X  模拟器都有

**Comment by iMazy** [comment]
I solved with ```edgesForExtendedLayout = []``` in  ```viewDidLoad( )```

**Comment by xiaoerlong** [comment]
> I solved with `edgesForExtendedLayout = []` in `viewDidLoad( )`

This also applies to me
