### ISSUE TITLE
不支持swift4.2

### ISSUE THREAD

**Issue by yinanwang1** [eggswift/pull-to-refresh#144]
每次pod install后，就提示错误。因为不支持swift 4.2版本，需要手动设置为swift 4.0后才可以。

**Comment by choiks14** [comment]
me too.

**Comment by hoangtuanfithou** [comment]
`post_install do |installer|

    swift4_pods = ['ExpandableLabel', 'UberRides', 'UberCore', 'ESPullToRefresh']

    installer.pods_project.targets.each do |target|

        if swift4_pods.include?(target.name)
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end

    end
end`

can try with this (put end of pod file)

**Comment by yinanwang1** [comment]
@hoangtuanfithou  Yes, that's ok by this way.
If the author will upgrade this framework, that will be better.
