### ISSUE TITLE
怎么判断是自己代码触发的刷新还是手动下拉触发的刷新？

### ISSUE THREAD

**Issue by derekcoder** [eggswift/pull-to-refresh#149]
或者说：我可不可以使用代码触发下拉的效果，但是不调用 handler

**Comment by eggswift** [comment]
可以.
self.tableView.es.addPullToRefresh {}
tableView.es.base.header?.handler = nil
这时候调用 
tableView.es.autoPullToRefresh() 则没有回调handle
你可以随后使用
tableView.es.base.header?.handler = { [weak self] in
            self?.refresh()
}
来为scrollView增加handle事件, 这样你就可以自己管理scrollview是否有下拉的真实事件了.
