### ISSUE TITLE
UICollectionView 无法使用问题

### ISSUE THREAD

**Issue by Johnson8888** [eggswift/pull-to-refresh#15]
当UICollectionView的
    func collectionView(collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 0
    }
时，下拉刷新无效?并且不在显示ESRefreshHeaderView

**Comment by harryzh** [comment]
我来替楼主回答吧
self.collectionView.alwaysBounceVertical = YES
参考
http://www.cocoachina.com/bbs/read.php?tid-272497.html

**Comment by eggswift** [comment]
UICollectionView默认alwaysBounceVertical 是 false的。
所以可以通过`self.collectionView.alwaysBounceVertical = true`来解决

**Comment by Johnson8888** [comment]
多谢 ~ 问题解决了 ~
