### ISSUE TITLE
Update the CocoaPods version.

### ISSUE THREAD

**Issue by lm2343635** [eggswift/pull-to-refresh#155]
Can you update the CocoaPods version for the latest release 2.8.
 https://github.com/eggswift/pull-to-refresh/releases/tag/2.8.
Thanks!

**Comment by eggswift** [comment]
ok https://github.com/eggswift/pull-to-refresh/releases/tag/2.9 for Xcode10.2

**Comment by lm2343635** [comment]
Hi @eggswift 
Can you update the CocoaPods version for 2.9?
The latest version in the CocoaPods repo is 2.7.
<img width="856" alt="Screen Shot 2019-04-17 at 13 08 26" src="https://user-images.githubusercontent.com/9463655/56260357-e53f9b00-6111-11e9-8b92-4c6fdb59b3f0.png">

**Comment by AppleTTT** [comment]
The same problem, github is 2.9 but CocoaPods version is still 2.7, hope @eggswift update CocoaPods
