### ISSUE TITLE
Update the CocoaPods version.

### ISSUE THREAD

**Issue by lm2343635** [eggswift/pull-to-refresh#159]
Can you update the CocoaPods version for the latest release 2.9.
I mean I want to install with the CocoaPods using
```ruby
pod 'ESPullToRefresh'
```
However, the latest version is 2.7.
<img width="856" alt="Screen Shot 2019-04-17 at 13 08 26" src="https://user-images.githubusercontent.com/9463655/56260357-e53f9b00-6111-11e9-8b92-4c6fdb59b3f0.png">

Can you update the CocoaPods version with
```Shell
pod trunk push ESPullToRefresh.podspec
```
Thanks!

**Comment by eggswift** [comment]
Done
