### ISSUE TITLE
Couldn't do pull to refresh when there is 1 or 2 items in UICollectionView

### ISSUE THREAD

**Issue by zaidqattan** [eggswift/pull-to-refresh#172]
Hello,
I'm working on a project and used your amazing library, my issue happens when I
 have 1 or 2 cells in the collection view and the scroll fits the screen so I couldn't be able to do the pull to refresh

![IMG_2267](https://user-images.githubusercontent.com/43964601/72639342-0fa6d900-396e-11ea-83f7-f54ada928c75.PNG)

**Comment by iamjjh** [comment]
set collection.bounce and alwaysBounceVertical true

**Comment by zaidqattan** [comment]
Thank you! it worked
