### ISSUE TITLE
【问题】建议

### ISSUE THREAD

**Issue by gzhongcheng** [eggswift/pull-to-refresh#174]
目前版本的代码在Pod库配置为Swift4.0时会报错，
请在podspec文件中添加下面的代码指定为Swift5可消除错误：
```
s.swift_version = "5.1"
```

**Comment by EngineHG** [comment]
![image](https://user-images.githubusercontent.com/8623979/75953227-e1646500-5eeb-11ea-97e7-7678c94a91c9.png)
 目前项目是swift是5，pod下来的时候会报这样的错误，楼上的建议应该是可以解决这个问题
