### ISSUE TITLE
Carthage not working update

### ISSUE THREAD

**Issue by thanhdevapp** [eggswift/pull-to-refresh#20]
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/eggswift/ESPullToRefresh.git /Users/thanhngoxuan/Library/Caches/org.carthage.CarthageKit/dependencies/ESPullToRefresh) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled

**Comment by dongfangx** [comment]
我也遇到同样的问题

**Comment by mallikarjunm034** [comment]
/Users/apple/Library/Caches/org.carthage.CarthageKit/dependencies/peertalk) failed with exit code 128:

getting this error any solution pls?
