### ISSUE TITLE
我用pod导入之后不能正常使用

### ISSUE THREAD

**Issue by zhanghongdou** [eggswift/pull-to-refresh#21]
self.tableView.es_addPullToRefresh {
            [weak self] in
            self?.tableView.es_stopPullToRefresh(completion: true)
            self?.tableView.es_stopPullToRefresh(completion: true, ignoreFooter: false)
        }

提示错误是：value of type “UITableView” has no member ' es_addPullToRefresh'

**Comment by zhanghongdou** [comment]
我手动导入的时候就可以识别，但是使用pod就不行了

**Comment by zhanghongdou** [comment]
请问楼主，这是什么原因导致的

**Comment by gaoyve** [comment]
https://github.com/eggswift/pull-to-refresh/issues/18
是因为手动导入ESPullToRefresh后相关类文件是直接可见的，相当于你自己在项目中创建了相关类
而Pod导入后只是在项目中添加了Framework，要使用的话还需要import，类比`import UIKit`

**Comment by zhanghongdou** [comment]
我添加了头文件的，但是还是不行，编译了几次都不行，我再试试吧

**Comment by zhanghongdou** [comment]
谢谢

**Comment by gaoyve** [comment]
能截图我看看吗？

**Comment by zhanghongdou** [comment]
可以，稍等

**Comment by zhanghongdou** [comment]
刚才写的让我删了，我又重新写了一遍，你看看

import UIKit
import ESPullToRefresh
class ViewController: UIViewController {

    @IBOutlet weak var tableView: UITableView!
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        self.tableView.es_addPullToRefresh {
            [weak self] in
            /// Do anything you want...
            /// ...
            /// Stop refresh when your job finished, it will reset refresh footer if completion is true
            self?.tableView.es_stopPullToRefresh(completion: true)
            /// Set ignore footer or not
            self?.tableView.es_stopPullToRefresh(completion: true, ignoreFooter: false)
        }
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}
![2016-08-01 4 21 59](https://cloud.githubusercontent.com/assets/16813719/17287772/1bf7a3fa-5804-11e6-8820-3b10f8fdbec7.png)

**Comment by zhanghongdou** [comment]
还是同样的问题，还是报这个错误

**Comment by zhanghongdou** [comment]
手动导入的话是没事的

**Comment by gaoyve** [comment]
<img width="1014" alt="screen shot 2016-08-01 at 16 32 52" src="https://cloud.githubusercontent.com/assets/11660168/17288076/b548682c-5805-11e6-9f07-6b0c1ad1aabf.png">
我这儿没问题啊😂

**Comment by gaoyve** [comment]
你像我这样截个图 我看看

**Comment by zhanghongdou** [comment]
。。。。。。。。。what，我截图给你看看

**Comment by zhanghongdou** [comment]
![2016-08-01 4 41 00](https://cloud.githubusercontent.com/assets/16813719/17288276/c8ffcb70-5806-11e6-9707-8709daec1fb2.png)
会不会是我xcode的原因，等会我重启一下电脑

**Comment by gaoyve** [comment]
clean一下试试

**Comment by zhanghongdou** [comment]
clean很多次，不行的，你的可以用，估计就是我电脑的原因了，

**Comment by zhanghongdou** [comment]
我先勉强按手动的来，等一下关机重启试试

**Comment by gaoyve** [comment]
嗯，多尝试可能就好了

**Comment by zhanghongdou** [comment]
再请教你一个问题，就是，self.tableView1.es_autoPullToRefresh()这个方法是开始进行刷拉刷新的操作是吧，但是我设置了没有反应是为什么

**Comment by gaoyve** [comment]
可以在Example里看看各方法的使用方法

**Comment by zhanghongdou** [comment]
恩恩谢谢

**Comment by zhanghongdou** [comment]
赞一颗星

**Comment by zhanghongdou** [comment]
![2016-08-01 5 18 38](https://cloud.githubusercontent.com/assets/16813719/17289375/081b1e5e-580c-11e6-846d-f99bde6292ad.png)
我上拉刷新的时候，会出现这种情况是什么导致的

**Comment by zhanghongdou** [comment]
我请求的内容一共有三页，但是，执行刷新第二页的内容的时候， 就出现，这个问题

**Comment by gaoyve** [comment]
没懂你的意思

**Comment by zhanghongdou** [comment]
就是我请求的内容一共有三页，第一页是执行下拉刷新，这个没有问题，然后我执行上拉刷新请求后端第二页的数据，刷新停止之后就出现了这个问题

**Comment by zhanghongdou** [comment]
我给你截图

**Comment by zhanghongdou** [comment]
![2016-08-01 5 24 41](https://cloud.githubusercontent.com/assets/16813719/17289580/e62eca06-580c-11e6-9c9c-4b26cc03f29a.png)
上面这个图是第一次请求（第一页的内容）
![2016-08-01 5 18 38](https://cloud.githubusercontent.com/assets/16813719/17289595/f7b6e038-580c-11e6-84ef-30690a63e300.png)
上面是执行shang刷新之后
![2016-08-01 5 24 56](https://cloud.githubusercontent.com/assets/16813719/17289612/05dbd830-580d-11e6-9a45-37616217908e.png)
再次执行上拉刷新

**Comment by zhanghongdou** [comment]
也就是第二图，出现了界面上那个问题

**Comment by zhanghongdou** [comment]
![2016-08-01 5 28 05](https://cloud.githubusercontent.com/assets/16813719/17289691/667aeac8-580d-11e6-8447-b29ac0249896.png)
![2016-08-01 5 28 24](https://cloud.githubusercontent.com/assets/16813719/17289693/67c2a7f4-580d-11e6-9ba4-a4d801ecc304.png)

**Comment by gaoyve** [comment]
目测我解决不了这个问题，得作者本人来看看了

**Comment by zhanghongdou** [comment]
好吧，谢谢哈

**Comment by zhanghongdou** [comment]
作者在吗，为什么会出现这个问题能不能解释一下，如果我是轻轻地上拉刷新的话，就没有问题，如果我太用力的话，就会出现，刷新之后，tableView便宜成我上面截图的位置

**Comment by eggswift** [comment]
Hi @zhanghongdou 非常感谢你参与这个开源项目，并积极优化目前存在问题。
针对你的项目，我觉得以下地方可以进行优化：
1、请求成功后
`self.tableView1.es_stopPullToRefresh(completion: true)`
`self.tableView1.es_stopPullToRefresh(completion: true, ignoreFooter:false)`
以上两个方法都试停止下拉刷新的方法，调用一个即可。
2、建议在stopPullToRefresh后再进行tableview insert data。

若依然出现以上问题，请邮箱发一份demo，我会尽快解决这个问题并给予你反馈。

**Comment by zhanghongdou** [comment]
不好意思，之前没看见，明天我上班的时候优化一下试试，然后在来这里给你留言

**Comment by zhanghongdou** [comment]
我想问，你们使用的时候没有出席那我这个问题吗，我现在吧self.tableView1.es_stopPullToRefresh(completion: true)
self.tableView1.es_stopPullToRefresh(completion: true, ignoreFooter:false)
这两个方法删除一个的时候，
运行就会出现一个问题就是：如果我用力上拉刷新的话它自己又启动了下拉刷新，如果我轻轻的上拉刷新当然是没有问题的，我想问这个为什么

**Comment by zhanghongdou** [comment]
就是说如果我用力上拉刷新的话（也不是特别用力，正常的使用力道），下拉刷新之后界面刷新，瞬间自己启动下拉刷新，表示不理解

**Comment by eggswift** [comment]
有一点晕 😂～ 可以分享一个小demo嘛？ 或许你也可以加入我们，尝试解决这个问题哟～

**Comment by zhanghongdou** [comment]
难道你们没有遇见过吗

**Comment by zhanghongdou** [comment]
我请求的数据是我们公司的，又有相关的加密方法，不能泄漏，我回头改改再发给你一个demo，同时我也很愿意加入你们😂

**Comment by eggswift** [comment]
我要关掉这个issue了～ 现在好像没有人再反馈这个问题了。
