### ISSUE TITLE
Not working if there are no items in the collection

### ISSUE THREAD

**Issue by amratab** [eggswift/pull-to-refresh#24]
Nothing happens if I try the pull down gesture on a empty UiCollectionView. This is a big issue as this is exactly the place where my users would want to check if something has been added on server.

**Comment by wspl** [comment]
+1, same problem here

**Comment by aitbaali** [comment]
any solution?

**Comment by eggswift** [comment]
Working on it~

**Comment by eggswift** [comment]
It not working because UICollectionView 's default `alwaysBounceVertical` is false.
Use `self.collectionView.alwaysBounceVertical = true` to solve this problem! : )
