### ISSUE TITLE
es_startPullToRefresh

### ISSUE THREAD

**Issue by fuboyou** [eggswift/pull-to-refresh#27]
代码如下，当我在一个tableViewController中为tableView添加了下拉刷新和上拉加载，当使用es_startPullToRefresh方法时，发现，下拉刷新和上拉加载都调用了一遍，正常应该是只有下拉刷新被调用，不确定我是不是个例，我的页面中还使用了UISearchController，谢谢
self.tableView.es_addPullToRefresh { [weak self] in
            guard self != nil else {return}
            self?.getData()
        }
        self.tableView.es_addInfiniteScrolling { [weak self] in
            guard self != nil else {return}
            self?.loadMoreData()
        }
        self.tableView.es_startPullToRefresh()

**Comment by eggswift** [comment]
请问你是使用的pod吗？

**Comment by fuboyou** [comment]
@eggswift 是的，我是使用的pod

**Comment by eggswift** [comment]
昨天我升级了一下Pod你升级一下，看看还有没有问题 😁

**Comment by fuboyou** [comment]
@eggswift pod是只更新了主分支吗，我这边暂时保守的使用了swift 2.3分支，并且我发现了一个新的问题，在CollectionView中，添加下拉刷新和上拉加载后，当数据不足一页，在上拉刷新结束设置的noMoreData没有生效，仍然可以上拉加载

**Comment by eggswift** [comment]
swift2.3现在不更新了~ 建议你升级到swift3来开发。
CollectionView的问题，我检查一下~

**Comment by fuboyou** [comment]
@eggswift thanks

**Comment by eggswift** [comment]
这个问题看上去已经解决了，我现在关闭这个issue，如果还有其他的问题，欢迎随时提问~

**Comment by adisonhyh** [comment]
这个问题我也遇到了，看起来并没有解决呀 @eggswift
