### ISSUE TITLE
先使用es_removeRefreshFooter 再使用 es_addInfiniteScrolling 发现tableview 末尾会出现空白

### ISSUE THREAD

**Issue by kunwang** [eggswift/pull-to-refresh#29]
if offset >= totalCount {
            self.tableView.es_removeRefreshFooter()
        } else if tableView.es_footer == nil {
            tableView.es_addInfiniteScrolling { [weak self] in
                self?.loadMore()
            }
        }

**Comment by eggswift** [comment]
I have to close this issue because it may be fixed by new version.
