### ISSUE TITLE
UITableView支持吗？下拉刷新也支持吗？

### ISSUE THREAD

**Issue by arden** [eggswift/pull-to-refresh#3]
UITableView支持吗？下拉刷新也支持吗？

**Comment by Geeerry** [comment]
都支持

**Comment by arden** [comment]
@Geeerry 应该是上拉刷新。

**Comment by Geeerry** [comment]
支持

**Comment by eggswift** [comment]
@arden 只要UIScrollView的子类都是支持的，例如UITableView, UICollectionView，UIWebView。目前交互形式上仅支持下拉刷新和加载更多，你说的上拉刷新是指.....?

**Comment by arden** [comment]
@eggswift 刚测试了下你的例子，都可以。
另外动画是不是能够直接支持gif图片呢？

**Comment by eggswift** [comment]
@arden Same as #5 : )
