### ISSUE TITLE
Carthage名称错误

### ISSUE THREAD

**Issue by gssdromen** [eggswift/pull-to-refresh#32]
github "eggswift/ESPullToRefresh"提示
*** Cloning ESPullToRefresh
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/eggswift/ESPullToRefresh.git /Users/cedricwu/Library/Caches/org.carthage.CarthageKit/dependencies/ESPullToRefresh) failed with exit code 128:
remote: Repository not found.
fatal: repository 'https://github.com/eggswift/ESPullToRefresh.git/' not found

应为 github "eggswift/pull-to-refresh"

**Comment by eggswift** [comment]
Its done by houssem-yahiaoui. : )
