### ISSUE TITLE
下拉图片获取为nil

### ISSUE THREAD

**Issue by happybobo** [eggswift/pull-to-refresh#46]
`UIImage(named: "icon_pull_to_refresh_arrow", in: Bundle(identifier: "com.eggswift.ESPullToRefresh"), compatibleWith: nil)`
获取图片为空

**Comment by happybobo** [comment]
不过可以通过自定义header解决

**Comment by eggswift** [comment]
@happybobo 请问你是通过pod还是carthage引入的？

**Comment by KaiZhang890** [comment]
是有这个问题，我是通过pod引入的

**Comment by eggswift** [comment]
@KaiZhang890 更新了一个版本，你可以更新至version 2.3试一下。圣诞节快乐！💐💐💐
