### ISSUE TITLE
Pod 安装之后没有箭头图片，collectionView 下拉刷新头部显示不全

### ISSUE THREAD

**Issue by tosslife** [eggswift/pull-to-refresh#49]
我下载源码添加进项目，图片资源是有了，可还是会出现头部显示不全的问题。请问该如何解决呢
注： 自定义的UICollectionViewLayout，正常layout没问题
用的这个自定义layout https://github.com/fdzsergio/SFFocusViewLayout

**Comment by eggswift** [comment]
可以邮件我一个demo吗？ 这种特殊的自定义flowlayout可能支持的不太好，我可以根据demo优化一下！

**Comment by tosslife** [comment]
@eggswift  您可以直接下载它的demo然后用您的下拉刷新试试

**Comment by laoyur** [comment]
@eggswift 请问没有箭头图标的问题怎么修复啊
  pod 'ESPullToRefresh', :git => 'https://github.com/eggswift/pull-to-refresh.git', :branch => 'swift2.3'

**Comment by eggswift** [comment]
@laoyur Hi Swift2.3的分支目前已经不维护了，你可以使用最新的。

**Comment by eggswift** [comment]
@tosslife 抱歉，SFFocusViewLayout的demo在xcode8.2.1上运行有问题，我现在要把这个issue关了。 如果你在使用中依然问题，请打开并与我联系~
