### ISSUE TITLE
你这个能否直接支持gif图片？

### ISSUE THREAD

**Issue by arden** [eggswift/pull-to-refresh#5]
你这个能否直接支持gif图片？而不是需要导入多张静态图。

**Comment by eggswift** [comment]
@arden  UIImageView本身不支持gif，你可以自定义一个支持gif的组件来支持。如果要添加到下拉刷新中，你可以自定义Animator，然后实现里面的协议。具体可以参考例子中的MTRefreshHeaderAnimator，把你的gif组件替换imageView。
