### ISSUE TITLE
Providing a pull to refresh description for the header title doesn't update the header's label

### ISSUE THREAD

**Issue by indieSoftware** [eggswift/pull-to-refresh#52]
Currently when providing a custom pull to refresh description for a header the text will only be used after the user has pulled the scroll view once. Before that, in its initial state and the user drags the view the library's default text will be shown. To prevent this I have to use a workaround:

```
let header = tableView.es_addPullToRefresh { [weak self] in
  self?.refreshData()
}
if let animator = header.animator as? ESRefreshHeaderAnimator {
  animator.loadingDescription = "My custom text"
  animator.pullToRefreshDescription = "My custom text"
  animator.releaseToRefreshDescription = "My custom text"
  animator.refreshAnimationEnd(view: header) // Workaround to update the header's label (ESPullToRefresh 2.4)
}
```

When setting the animator.pullToRefreshDescription property it should instantly update the header's label with the given string when in the pullToRefresh state.

**Comment by eggswift** [comment]
Same as #51

**Comment by eggswift** [comment]
I'm going to close this issue, because this bug has fixed in master branch. : )
