### ISSUE TITLE
When refreshing and scrolling section headers don't stick with the top

### ISSUE THREAD

**Issue by indieSoftware** [eggswift/pull-to-refresh#53]
When pulling to refresh and releasing the table view goes into the fetch new data mode (refreshing). While the data in the background is beeing loaded the user scrolls the table view. The table view has multiple sections with corresponding section headers. While scrolling the section headers normally stick on the table view's top, but not when currently refreshing. In the refreshing state between the section header and the table view's top border is a gap, but shouldn't.

This is because the lib uses insets when refreshing. These results in the gap because the section headers respect the inset, but should stick with the border.

See for a possible solution:
http://stackoverflow.com/questions/5466097/section-headers-in-uitableview-when-inset-of-tableview-is-changed

**Comment by eggswift** [comment]
@indieSoftware Thanks, It's a good problem. I have tried to fix it, and pushed it into remote just now. You can download the updates, and find it works or not. Please give me any feedback after your update.

**Comment by indieSoftware** [comment]
Confirmed, it works, thanks!
