### ISSUE TITLE
load more 展示错误

### ISSUE THREAD

**Issue by QiuZhiFei** [eggswift/pull-to-refresh#57]
![simulator screen shot 2017 1 21 12 30 37](https://cloud.githubusercontent.com/assets/3402799/22171946/79136da4-dfd5-11e6-8634-eae504cf50b6.png)

Demo 最后一页，预期为  『No more data』，实际 『Loading more』

-------

查看源码

```
// Back state
        UIView.animate(withDuration: 0.3, delay: 0, options: .curveLinear, animations: {
        }, completion: { (finished) in
            self.animator.refresh(view: self, stateDidChange: .pullToRefresh)
            super.stop()
        })
```

stop 函数结束后，默认变更为了 pullToRefresh 导致的 ... 这里重置为 pullToRefresh 的原因是？

期待您的回复。

**Comment by eggswift** [comment]
看起来的确有这个问题，稍后我来修复一下，也欢迎提交PR
