### ISSUE TITLE
使用默认样式 下拉箭头不见了

### ISSUE THREAD

**Issue by jerry0317** [eggswift/pull-to-refresh#59]
最新2.6 使用默认，发现下拉的时候没有箭头

**Comment by eggswift** [comment]
请问你是用什么方式集成的?

**Comment by jerry0317** [comment]
用README里面的默认方法

`self.someScrollView.es_addPullToRefresh{
            [weak self] in
            /// Do anything you want...
            /// ...
            
        }`

**Comment by jerry0317** [comment]
找到问题了，原先这个文件没有被加到Copy Bundle Resources里面
![screen shot 2017-02-07 at 10 37 54 am](https://cloud.githubusercontent.com/assets/10691532/22675586/97d40cf4-ed21-11e6-960b-5afbf50bda0c.png)

**Comment by eggswift** [comment]
看到你用的是CocoaPods，图片文件正常应该在ESPullToRefresh.bundle里

**Comment by jerry0317** [comment]
嗯，bundle里确实有，但是运行的时候没法显示箭头，我加在上面那张图的ESPullToRefresh里面才正常

**Comment by eggswift** [comment]
哦，那这是个问题，我看一下

**Comment by jerry0317** [comment]
好的，谢谢！

**Comment by eggswift** [comment]
@jerry0317  hi 我修改好了，你可以手动设置pod到master，更新到最新

**Comment by jerry0317** [comment]
好的谢谢！不过请问怎么设置pod到master😂

**Comment by eggswift** [comment]
额，你先把箭头图片资源放在工程里吧，我看看最近要修改的其他东西，弄好以后重新加一个tag。如果你遇到其他问题，可以告诉我。

**Comment by jerry0317** [comment]
ok，谢谢
