### ISSUE TITLE
Support other languages?

### ISSUE THREAD

**Issue by Sweeper777** [eggswift/pull-to-refresh#61]
Can you localize this pod for other languages, like zh-Hans, zh-Hant and jp?

**Comment by eggswift** [comment]
You can subclass content and customize strings.

**Comment by Sweeper777** [comment]
Which class do I subclass? Can I just send you a pull request?

**Comment by eggswift** [comment]
Sure it's welcome!

**Comment by eggswift** [comment]
#65 
Merged

**Comment by paulg446** [comment]
Wouldn't it make more sense to allow localization/customization of strings via an API as opposed to hard-coding strings into the project? Something like a global static object where string values can be overridden would ideal. There are only a few strings, it should be simple.  Great library, by the way! Very useful.
