### ISSUE TITLE
Swift 3? Support?

### ISSUE THREAD

**Issue by htarwara6245** [eggswift/pull-to-refresh#63]
Any Help with that?

**Comment by eggswift** [comment]
Any problem?

**Comment by htarwara6245** [comment]
No nothing. I just worried about using Swift 2.3 and 3 framework in parallel might come in some error at archiving. That's all. Your library worked perfectly well. Thanks to you

**Comment by eggswift** [comment]
If you have any question about using this framework, please publish issues for free!
