### ISSUE TITLE
Editing Text and Font for default pull to refresh and load more?

### ISSUE THREAD

**Issue by htarwara6245** [eggswift/pull-to-refresh#64]
Is there any way that I can edit the text of pull to refresh, load more and no more data without making new customize refresh control by using default control

Any Help?

**Comment by eggswift** [comment]
You need to customize an ESRefreshHeaderAnimator subclass.

**Comment by cancem123** [comment]
Please can you explain how to customize ESRefreshHeaderAnimator? I just need to edit the text.

**Comment by cancem123** [comment]
@htarwara6245 and @eggswift can you please explain how to customize ESRefreshHeaderAnimator?
