### ISSUE TITLE
请问能定制显示的内容么？

### ISSUE THREAD

**Issue by hoody4032** [eggswift/pull-to-refresh#7]
在class ESRefreshHeaderAnimator中定义了pullToRefreshDescription。用户可以改动么？

我想像网易那样，在下拉刷新时能显示离上次刷新的时间。请问现在能做到么？如果不能，能否考虑加进去？

多谢。

**Comment by Geeerry** [comment]
很好的点子，考虑添加此特性
^_^

**Comment by eggswift** [comment]
@hoody4032 
1、设置刷新时间；
2、设置过期时间；
3、策略刷新。
当前trank下已经支持！稍后会在1.0.4版本中添加到Pod中。
感谢你的支持 😄
