### ISSUE TITLE
pod 的版本内容和download的源码目录不一样？

### ISSUE THREAD

**Issue by huxq-coder** [eggswift/pull-to-refresh#75]
let header = ESRefreshHeaderAnimator(frame: CGRect.zero)
        self.tableView.es_addPullToRefresh(animator: header) { 
            [weak self] in
            self?.page_num = 0
            self?.load()
        }
        self.tableView.es_startPullToRefresh()

调用之后默认不显示下拉刷新的箭头？
请问是否可以显示最后刷新时间？
谢谢，465310135@qq.com

**Comment by codwam** [comment]
👍

**Comment by eggswift** [comment]
Done!
