### ISSUE TITLE
Footer is sticked after call of stopLoadingMore()

### ISSUE THREAD

**Issue by MiteshiOS** [eggswift/pull-to-refresh#80]
For loadMore data when there is no more data i stopped loader by calling this method **self.tableView.es.stopLoadingMore()** but the footer is still there saying "Loading more".

What should i do if i want to remove this one.
![screen shot 2017-06-28 at 12 57 56 pm](https://user-images.githubusercontent.com/17427703/27625535-989eff4a-5c02-11e7-8d1c-a08734c6e2c8.png)

**Comment by malkabani** [comment]
SO, How to fix it?
