### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by codwam** [eggswift/pull-to-refresh#86]
Fixed bugs:
1. Push controller while refresh then pop the scrollview inset was wrong?
2. Localization for chinese?
3. The arrow not show?

**Comment by xiaozao2008** [comment]
@codwam  
2. have Localization for Chinese
3. that's a image in Source Document
1. An Controller(VC1) refreshing then pop,  VC1's scrollview inset?

**Comment by codwam** [comment]
1.`VC1` refreshing then push, and the `titleLabel` show below the navigationBar while the `VC2` pop.
2.You can changed the simulator the see it's always english.
3.You can test `Cocoapods`, the arrow image not show

I have download the latest code, it's different to the latest release version `2.6`
