### ISSUE TITLE
Carthage support not working

### ISSUE THREAD

**Issue by oonoo** [eggswift/pull-to-refresh#9]
I can't use your lib with carthage. For carthage to work you must have shared your Xcode scheme like that: https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework

**Comment by danjiang** [comment]
github "eggswift/ESPullToRefresh" is not same with github repository https://github.com/eggswift/pull-to-refresh

**Comment by eggswift** [comment]
@danjiang The new version is in beta. It will available soon.
