### ISSUE TITLE
Adapter Swift4

### ISSUE THREAD

**Issue by xiaobs** [eggswift/pull-to-refresh#94]

**Comment by piv199** [comment]
@eggswift do you need any help for this task?

**Comment by Pulichev** [comment]
How can I fast fix "Declarations from extensions cannot be overridden yet"? :(

**Comment by xiaobs** [comment]
<img width="332" alt="default" src="https://user-images.githubusercontent.com/7802080/30673244-3dde3a0a-9ea4-11e7-8645-29de50fc1ada.png">

Hello, please resolve “declarations in extensions cannot override yet” in Swift4

**Comment by Pulichev** [comment]
Should we just make from an extension a subclass?

**Comment by Pulichev** [comment]
I think, that this pod is unsupported :(

**Comment by piv199** [comment]
@Pulichev have you tried any other similar pods with swift4

**Comment by Pulichev** [comment]
@piv199 no
I'll think some time, how can I fix this. If no ideas - will look for a new

**Comment by eggswift** [comment]
@piv199 @Pulichev @xiaobs 
Sorry about my heavy works these days.
I'll fix it this week. 
Thanks for this issue.

**Comment by xiaobs** [comment]
Waiting for your update.
Thank you very much!

**Comment by Pulichev** [comment]
Wow! Thank you so much for supporting!:)

**Comment by siberianisaev** [comment]
temp fix added `pod 'ESPullToRefresh', :git => 'https://github.com/siberianisaev/pull-to-refresh.git', :commit => '702aa5aa01515818c96a2986f14def6a71445848'` (now sure correct or not, but working for me)

Separate issue. In the client code `es_` prefix must be replaced with `es.`. Need to update Readme

**Comment by Pulichev** [comment]
I have also fixed it. 

commented like 

//}

//public extension ESRefreshComponent /* Action */ {

in ESPullToRefresh 
and ESRefreshComponent

Find this places.

Also added @objc prefix to problematic functions.

Good luck

**Comment by annjawn** [comment]
@siberianisaev your code works perfectly. It should be merged to master and the documentation should be updated with the `es.` bit.
